server_addr: http://192.168.1.33:8888

limit: 2

enc_option:
  parentDir: Enc-Rec3_ext5
  # ディレクトリオプションを利用しない場合はNoneを入力
  directory: None
  isSaveSameDirectory: false
  mode: H.264
  removeOriginal: false

# ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level: INFO
